title: Movember Study
author: Carly Barton
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This project is going to focus on overactivr bladder in men newly diagnosed with prostate cancer, and if treatment for prostate cancer 
  makes said OAB worse, better, or creates OAB entirely. 

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
